export const refs = {
  form: document.querySelector('.search-form'),
  homePage: document.querySelector('[data-home]'),
  libraryPage: document.querySelector('[data-library]'),
  header: document.querySelector('[data-header]'),
  libraryBtns: document.querySelector('.library-buttons'),
  watchedBtn: document.querySelector('[data-watched]'),
  queueBtn: document.querySelector('[data-queue]'),
  message: document.querySelector('.message'),
  preloader: document.querySelector('.loading'),
  gallery: document.querySelector('.gallery-list'),
  backdrop: document.querySelector('.js-backdrop'),
  modal: document.querySelector('.modal__wrapper'),
  closeModalBtn: document.querySelector('.js-modal__close-btn'),
};
